"""Parity test: interlace CS vs R nlme, compound symmetry residual correlation.

Model:  y ~ x, random = ~1|group, correlation = corCompSymm(form = ~1|group)
Data:   300 obs, 30 groups, 10 time points  (tests/fixtures/cs_parity_data.csv)
Oracle: tests/fixtures/cs_parity_r_results.json  (generated by gen_cs_parity.R)

R equivalent:
    lme(y ~ x, random = ~1|group,
        correlation = corCompSymm(form = ~1|group),
        data = df, method = "REML")

NOTE ON IDENTIFIABILITY:
    Random intercept + compound symmetry on the same grouping are not
    separately identifiable.  Both produce exchangeable within-group
    correlation, so the marginal covariance V_g = sigma_e^2*(1-rho)*I +
    [sigma_int^2 + sigma_e^2*rho]*J is invariant along a 1-D manifold.
    nlme absorbs CS into the random intercept (rho -> 0).

    This test therefore compares IDENTIFIABLE quantities:
      - Fixed effects (determined by V, always unique)
      - REML log-likelihood (function of V, always unique)
      - Marginal ICC = (var_int + var_resid*rho) / (var_int + var_resid)
      - Conditional residuals

    The R fixture also includes a gls() fit (no random effects, CS only)
    which estimates rho without identifiability issues -- this is used as
    ground truth for the marginal ICC.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import interlace
from interlace.correlation import CompoundSymmetry

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="module")
def data() -> pd.DataFrame:
    return pd.read_csv(FIXTURES / "cs_parity_data.csv")


@pytest.fixture(scope="module")
def r_results() -> dict:
    return json.loads((FIXTURES / "cs_parity_r_results.json").read_text())


@pytest.fixture(scope="module")
def il_result(data):
    return interlace.fit(
        formula="y ~ x",
        data=data,
        groups="group",
        correlation=CompoundSymmetry("time"),
    )


def _marginal_icc(result) -> float:
    """Compute marginal ICC for a model with random intercept + CS.

    ICC = (var_int + var_resid * rho) / (var_int + var_resid)
    """
    var_int = float(result.variance_components["group"])
    var_resid = result.scale
    rho = result.correlation_params.get("rho", 0.0)
    total = var_int + var_resid
    return (var_int + var_resid * rho) / total


def test_model_converged(il_result):
    assert il_result.converged, "Model did not converge"


def test_fixed_effects_match(il_result, r_results):
    """Fixed effects are identifiable regardless of variance decomposition."""
    r_fe = r_results["lme"]["fe_params"]
    name_map = {"(Intercept)": "Intercept", "x": "x"}
    for r_name, il_name in name_map.items():
        diff = abs(il_result.fe_params[il_name] - r_fe[r_name])
        assert diff < 0.05, (
            f"Fixed effect '{il_name}' abs_diff={diff:.4f} "
            f"(interlace={il_result.fe_params[il_name]:.6f}, R={r_fe[r_name]:.6f})"
        )


def test_reml_loglik_match(il_result, r_results):
    """REML log-likelihood is identifiable (function of marginal V only)."""
    r_ll = r_results["lme"]["loglik"]
    il_ll = il_result.llf
    diff = abs(il_ll - r_ll)
    assert diff < 0.5, (
        f"REML loglik abs_diff={diff:.4f} "
        f"(interlace={il_ll:.4f}, R={r_ll:.4f})"
    )


def test_marginal_icc_match(il_result, r_results):
    """Marginal ICC should match the R gls reference (clean, no identifiability issue).

    The gls fit estimates rho directly (no random intercept), so rho_gls IS
    the marginal ICC.  For interlace, ICC = (var_int + var_resid*rho) / total.
    """
    r_icc = r_results["gls"]["rho"]  # gls rho = marginal ICC
    il_icc = _marginal_icc(il_result)
    diff = abs(il_icc - r_icc)
    assert diff < 0.05, (
        f"Marginal ICC abs_diff={diff:.4f} "
        f"(interlace={il_icc:.4f}, R_gls={r_icc:.4f})"
    )


def test_total_marginal_variance(il_result, r_results):
    """Total marginal variance (var_int + var_resid) should match R."""
    r_total = r_results["lme"]["total_var"]
    il_var_int = float(il_result.variance_components["group"])
    il_total = il_var_int + il_result.scale
    rel_diff = abs(il_total - r_total) / r_total
    assert rel_diff < 0.05, (
        f"Total marginal variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_total:.6f}, R={r_total:.6f})"
    )


def test_blups_correlated(il_result, r_results):
    """Random intercept BLUPs should be highly correlated with R's."""
    r_blups = r_results["lme"]["blups"]
    labels = sorted(r_blups.keys())
    r_arr = np.array([r_blups[g] for g in labels])
    il_re = il_result.random_effects["group"]
    il_arr = il_re.loc[labels].to_numpy().ravel()
    corr = np.corrcoef(r_arr, il_arr)[0, 1]
    assert corr > 0.99, f"BLUP correlation={corr:.4f} < 0.99"


def test_residuals_correlated(il_result, r_results):
    """Conditional residuals should be highly correlated with R's."""
    r_resid = np.array(r_results["lme"]["resid_cond"])
    corr = np.corrcoef(il_result.resid, r_resid)[0, 1]
    assert corr > 0.98, f"Residual correlation={corr:.6f} < 0.98"
