"""Tests for Kenward-Roger adjusted covariance and denominator DFs.

Validates interlace's KR implementation against R's pbkrtest::vcovAdj()
and lmerTest::summary(ddf="Kenward-Roger").

Reference values generated by: Rscript tests/fixtures/gen_kr_parity.R
Requires: lme4, pbkrtest, lmerTest, jsonlite
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import interlace
from interlace.kenward_roger import kenward_roger

FIXTURES = Path(__file__).parent / "fixtures"


def _load_fixture(name: str) -> dict:
    with open(FIXTURES / name) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# One-factor model: y ~ x + (1 | group)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def one_factor():
    """Load R fixture and fit the same model in interlace."""
    ref = _load_fixture("kr_parity_one_factor.json")
    df = pd.DataFrame(
        {
            "y": np.array(ref["y"]),
            "x": np.array(ref["x"]),
            "group": [str(g) for g in ref["group"]],
        }
    )
    result = interlace.fit("y ~ x", data=df, groups="group")
    return ref, result


class TestOneFactorKR:
    """KR parity: y ~ x + (1 | group), 15 groups x 8 obs."""

    def test_kr_vcov_adj_matches_r(self, one_factor):
        """KR-adjusted FE covariance should match R's vcovAdj()."""
        ref, result = one_factor
        r_kr_adj = np.array(ref["kr_vcov_adj"])
        C_adj, _ = kenward_roger(result)
        np.testing.assert_allclose(C_adj, r_kr_adj, rtol=0.01)

    def test_kr_dfs_intercept_matches_r(self, one_factor):
        """KR DF for intercept should match R's lmerTest."""
        ref, result = one_factor
        r_df_intercept = ref["kr_dfs"]["(Intercept)"]
        _, dfs = kenward_roger(result)
        np.testing.assert_allclose(dfs[0], r_df_intercept, rtol=0.01)

    def test_kr_dfs_slope_matches_r(self, one_factor):
        """KR DF for slope should match R's lmerTest."""
        ref, result = one_factor
        r_df_x = ref["kr_dfs"]["x"]
        _, dfs = kenward_roger(result)
        np.testing.assert_allclose(dfs[1], r_df_x, rtol=0.01)


# ---------------------------------------------------------------------------
# Two-factor model: y ~ x + (1 | g1) + (1 | g2)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def two_factor():
    """Load R fixture and fit the same model in interlace."""
    ref = _load_fixture("kr_parity_two_factor.json")
    df = pd.DataFrame(
        {
            "y": np.array(ref["y"]),
            "x": np.array(ref["x"]),
            "g1": [str(g) for g in ref["g1"]],
            "g2": [str(g) for g in ref["g2"]],
        }
    )
    result = interlace.fit("y ~ x", data=df, random=["(1|g1)", "(1|g2)"])
    return ref, result


class TestTwoFactorKR:
    """KR parity: y ~ x + (1 | g1) + (1 | g2), crossed 10 x 6 groups."""

    def test_kr_vcov_adj_matches_r(self, two_factor):
        """KR-adjusted FE covariance should match R's vcovAdj()."""
        ref, result = two_factor
        r_kr_adj = np.array(ref["kr_vcov_adj"])
        C_adj, _ = kenward_roger(result)
        np.testing.assert_allclose(C_adj, r_kr_adj, rtol=0.01)

    def test_kr_dfs_intercept_matches_r(self, two_factor):
        """KR DF for intercept should match R's lmerTest."""
        ref, result = two_factor
        r_df_intercept = ref["kr_dfs"]["(Intercept)"]
        _, dfs = kenward_roger(result)
        np.testing.assert_allclose(dfs[0], r_df_intercept, rtol=0.01)

    def test_kr_dfs_slope_matches_r(self, two_factor):
        """KR DF for slope should match R's lmerTest."""
        ref, result = two_factor
        r_df_x = ref["kr_dfs"]["x"]
        _, dfs = kenward_roger(result)
        np.testing.assert_allclose(dfs[1], r_df_x, rtol=0.01)


# ---------------------------------------------------------------------------
# Properties: KR adjustments should have expected characteristics
# ---------------------------------------------------------------------------


class TestKRProperties:
    """Test structural properties of the KR adjustment."""

    def test_c_adj_symmetric(self, one_factor):
        _, result = one_factor
        C_adj, _ = kenward_roger(result)
        np.testing.assert_allclose(C_adj, C_adj.T, atol=1e-12)

    def test_c_adj_positive_diagonal(self, one_factor):
        _, result = one_factor
        C_adj, _ = kenward_roger(result)
        assert np.all(np.diag(C_adj) > 0)

    def test_dfs_positive(self, one_factor):
        _, result = one_factor
        _, dfs = kenward_roger(result)
        assert np.all(dfs >= 1.0)

    def test_kr_dfs_finite(self, two_factor):
        _, result = two_factor
        _, dfs = kenward_roger(result)
        assert np.all(np.isfinite(dfs))

    def test_kr_dfs_differ_from_satterthwaite(self, one_factor):
        """KR DFs should differ from Satterthwaite for the slope coefficient.

        The slope's variance depends heavily on σ²_resid, which is profiled
        out in Satterthwaite but treated as a free parameter in KR.  This
        gives a substantially lower (more conservative) DF.
        """
        from interlace.satterthwaite import satterthwaite_dfs

        _, result = one_factor
        _, kr_dfs = kenward_roger(result)
        satt_dfs = satterthwaite_dfs(result)

        # For the slope coefficient, KR should give a much smaller DF
        # (profiled Satterthwaite overestimates slope DF by ~8x)
        assert kr_dfs[1] < satt_dfs[1] * 0.5
