"""Parity tests against lme4 canonical vignette datasets.

Covers three models from the lme4 paper / vignette (Bates et al. 2015):

  Dyestuff   :  Yield     ~ 1           + (1         | Batch)    single RE
  sleepstudy :  Reaction  ~ Days        + (Days       | Subject)  corr. slopes
  Pastes     :  strength  ~ 1           + (1          | batch/cask) nested RE

Fixtures generated by:  tests/fixtures/gen_lme4_vignette.R

Acceptance criteria (from CLAUDE.md):
  - Fixed effects abs_diff < 1e-4
  - Variance components rel_diff < 5%
  - BLUP correlation > 0.99
  - Conditional residual correlation > 0.999
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import interlace

FIXTURES = Path(__file__).parent / "fixtures"


# ===========================================================================
# Dyestuff  —  Yield ~ 1 + (1 | Batch)
# ===========================================================================


@pytest.fixture(scope="module")
def dyestuff_data() -> pd.DataFrame:
    return pd.read_csv(FIXTURES / "lme4_dyestuff_data.csv")


@pytest.fixture(scope="module")
def dyestuff_ref() -> dict:
    return json.loads((FIXTURES / "lme4_dyestuff_results.json").read_text())


@pytest.fixture(scope="module")
def dyestuff_fit(dyestuff_data):
    return interlace.fit("Yield ~ 1", data=dyestuff_data, groups="Batch")


def test_dyestuff_intercept(dyestuff_fit, dyestuff_ref):
    r_val = dyestuff_ref["fe_params"]["(Intercept)"]
    il_val = dyestuff_fit.fe_params["Intercept"]
    diff = abs(il_val - r_val)
    assert diff < 1e-4, (
        f"Intercept abs_diff={diff:.2e} (interlace={il_val:.4f}, R={r_val:.4f})"
    )


def test_dyestuff_batch_variance(dyestuff_fit, dyestuff_ref):
    vc = dyestuff_ref["vc_table"]
    r_var_batch = next(row["vcov"] for row in vc if row["grp"] == "Batch")
    il_var_batch = dyestuff_fit.variance_components["Batch"]
    rel_diff = abs(il_var_batch - r_var_batch) / r_var_batch
    assert rel_diff < 0.05, (
        f"Batch variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var_batch:.4f}, R={r_var_batch:.4f})"
    )


def test_dyestuff_residual_variance(dyestuff_fit, dyestuff_ref):
    vc = dyestuff_ref["vc_table"]
    r_var_resid = next(row["vcov"] for row in vc if row["grp"] == "Residual")
    il_var_resid = dyestuff_fit.scale
    rel_diff = abs(il_var_resid - r_var_resid) / r_var_resid
    assert rel_diff < 0.05, (
        f"Residual variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var_resid:.4f}, R={r_var_resid:.4f})"
    )


def test_dyestuff_blups(dyestuff_fit, dyestuff_ref):
    r_blups = dyestuff_ref["ranef"]["Batch"]["(Intercept)"]
    labels = sorted(r_blups.keys())
    r_arr = np.array([r_blups[g] for g in labels])
    il_arr = np.array([dyestuff_fit.random_effects["Batch"][g] for g in labels])
    corr = np.corrcoef(r_arr, il_arr)[0, 1]
    assert corr > 0.99, f"Batch BLUP correlation={corr:.4f} < 0.99"


def test_dyestuff_residuals(dyestuff_fit, dyestuff_ref):
    r_resid = np.array(dyestuff_ref["resid_cond"])
    corr = np.corrcoef(dyestuff_fit.resid, r_resid)[0, 1]
    assert corr > 0.999, f"Residual correlation={corr:.6f} < 0.999"


# ===========================================================================
# sleepstudy  —  Reaction ~ Days + (Days | Subject)
# ===========================================================================


@pytest.fixture(scope="module")
def sleepstudy_data() -> pd.DataFrame:
    return pd.read_csv(FIXTURES / "lme4_sleepstudy_data.csv")


@pytest.fixture(scope="module")
def sleepstudy_ref() -> dict:
    return json.loads((FIXTURES / "lme4_sleepstudy_results.json").read_text())


@pytest.fixture(scope="module")
def sleepstudy_fit(sleepstudy_data):
    return interlace.fit(
        "Reaction ~ Days",
        data=sleepstudy_data,
        random=["(1 + Days | Subject)"],
    )


def test_sleepstudy_fixed_intercept(sleepstudy_fit, sleepstudy_ref):
    r_val = sleepstudy_ref["fe_params"]["(Intercept)"]
    il_val = sleepstudy_fit.fe_params["Intercept"]
    diff = abs(il_val - r_val)
    assert diff < 1e-4, (
        f"Intercept abs_diff={diff:.2e} (interlace={il_val:.4f}, R={r_val:.4f})"
    )


def test_sleepstudy_fixed_days(sleepstudy_fit, sleepstudy_ref):
    r_val = sleepstudy_ref["fe_params"]["Days"]
    il_val = sleepstudy_fit.fe_params["Days"]
    diff = abs(il_val - r_val)
    assert diff < 1e-4, (
        f"Days abs_diff={diff:.2e} (interlace={il_val:.6f}, R={r_val:.6f})"
    )


def test_sleepstudy_var_intercept(sleepstudy_fit, sleepstudy_ref):
    vc = sleepstudy_ref["vc_table"]
    r_var = next(
        row["vcov"]
        for row in vc
        if row["grp"] == "Subject"
        and row["var1"] == "(Intercept)"
        and row.get("var2") is None
    )
    # variance_components["Subject"] is the 2×2 covariance matrix DataFrame
    il_var = float(
        sleepstudy_fit.variance_components["Subject"].loc["(Intercept)", "(Intercept)"]
    )
    rel_diff = abs(il_var - r_var) / r_var
    assert rel_diff < 0.05, (
        f"Subject intercept variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var:.4f}, R={r_var:.4f})"
    )


def test_sleepstudy_var_slope(sleepstudy_fit, sleepstudy_ref):
    vc = sleepstudy_ref["vc_table"]
    r_var = next(
        row["vcov"]
        for row in vc
        if row["grp"] == "Subject" and row["var1"] == "Days" and row.get("var2") is None
    )
    il_var = float(sleepstudy_fit.variance_components["Subject"].loc["Days", "Days"])
    rel_diff = abs(il_var - r_var) / r_var
    assert rel_diff < 0.05, (
        f"Subject slope variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var:.4f}, R={r_var:.4f})"
    )


def test_sleepstudy_residual_variance(sleepstudy_fit, sleepstudy_ref):
    vc = sleepstudy_ref["vc_table"]
    r_var_resid = next(row["vcov"] for row in vc if row["grp"] == "Residual")
    il_var_resid = sleepstudy_fit.scale
    rel_diff = abs(il_var_resid - r_var_resid) / r_var_resid
    assert rel_diff < 0.05, (
        f"Residual variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var_resid:.4f}, R={r_var_resid:.4f})"
    )


def test_sleepstudy_blups_intercept(sleepstudy_fit, sleepstudy_ref):
    r_blups = sleepstudy_ref["ranef"]["Subject"]["(Intercept)"]
    # lme4 JSON keys are strings; interlace Series index is int — sort numerically
    labels_int = sorted(int(s) for s in r_blups)
    r_arr = np.array([r_blups[str(s)] for s in labels_int])
    il_series = sleepstudy_fit.random_effects["Subject"]["(Intercept)"]
    il_arr = np.array([il_series[s] for s in labels_int])
    corr = np.corrcoef(r_arr, il_arr)[0, 1]
    assert corr > 0.99, f"Subject intercept BLUP correlation={corr:.4f} < 0.99"


def test_sleepstudy_blups_slope(sleepstudy_fit, sleepstudy_ref):
    r_blups = sleepstudy_ref["ranef"]["Subject"]["Days"]
    labels_int = sorted(int(s) for s in r_blups)
    r_arr = np.array([r_blups[str(s)] for s in labels_int])
    il_series = sleepstudy_fit.random_effects["Subject"]["Days"]
    il_arr = np.array([il_series[s] for s in labels_int])
    corr = np.corrcoef(r_arr, il_arr)[0, 1]
    assert corr > 0.99, f"Subject slope BLUP correlation={corr:.4f} < 0.99"


def test_sleepstudy_residuals(sleepstudy_fit, sleepstudy_ref):
    r_resid = np.array(sleepstudy_ref["resid_cond"])
    corr = np.corrcoef(sleepstudy_fit.resid, r_resid)[0, 1]
    assert corr > 0.999, f"Residual correlation={corr:.6f} < 0.999"


# ===========================================================================
# Pastes  —  strength ~ 1 + (1 | batch/cask)
# ===========================================================================


@pytest.fixture(scope="module")
def pastes_data() -> pd.DataFrame:
    return pd.read_csv(FIXTURES / "lme4_pastes_data.csv")


@pytest.fixture(scope="module")
def pastes_ref() -> dict:
    return json.loads((FIXTURES / "lme4_pastes_results.json").read_text())


@pytest.fixture(scope="module")
def pastes_fit(pastes_data):
    return interlace.fit("strength ~ 1", data=pastes_data, random=["(1|batch/cask)"])


def test_pastes_intercept(pastes_fit, pastes_ref):
    r_val = pastes_ref["fe_params"]["(Intercept)"]
    il_val = pastes_fit.fe_params["Intercept"]
    diff = abs(il_val - r_val)
    assert diff < 1e-4, (
        f"Intercept abs_diff={diff:.2e} (interlace={il_val:.4f}, R={r_val:.4f})"
    )


def test_pastes_batch_variance(pastes_fit, pastes_ref):
    vc = pastes_ref["vc_table"]
    r_var = next(row["vcov"] for row in vc if row["grp"] == "batch")
    il_var = pastes_fit.variance_components["batch"]
    rel_diff = abs(il_var - r_var) / r_var
    assert rel_diff < 0.05, (
        f"batch variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var:.4f}, R={r_var:.4f})"
    )


def test_pastes_cask_batch_variance(pastes_fit, pastes_ref):
    vc = pastes_ref["vc_table"]
    # lme4 names the nested term "cask:batch"; interlace names it "batch:cask"
    r_var = next(row["vcov"] for row in vc if row["grp"] == "cask:batch")
    il_var = pastes_fit.variance_components["batch:cask"]
    rel_diff = abs(il_var - r_var) / r_var
    assert rel_diff < 0.05, (
        f"batch:cask variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var:.4f}, R={r_var:.4f})"
    )


def test_pastes_residual_variance(pastes_fit, pastes_ref):
    vc = pastes_ref["vc_table"]
    r_var_resid = next(row["vcov"] for row in vc if row["grp"] == "Residual")
    il_var_resid = pastes_fit.scale
    rel_diff = abs(il_var_resid - r_var_resid) / r_var_resid
    assert rel_diff < 0.05, (
        f"Residual variance rel_diff={rel_diff:.2%} "
        f"(interlace={il_var_resid:.4f}, R={r_var_resid:.4f})"
    )


def test_pastes_blups_batch(pastes_fit, pastes_ref):
    r_blups = pastes_ref["ranef"]["batch"]["(Intercept)"]
    labels = sorted(r_blups.keys())
    r_arr = np.array([r_blups[g] for g in labels])
    il_arr = np.array([pastes_fit.random_effects["batch"][g] for g in labels])
    corr = np.corrcoef(r_arr, il_arr)[0, 1]
    assert corr > 0.99, f"batch BLUP correlation={corr:.4f} < 0.99"


def test_pastes_blups_cask_batch(pastes_fit, pastes_ref):
    # lme4 labels the nested levels as "cask:batch" (e.g. "a:A");
    # interlace stores them as "batch:cask" (e.g. "A:a") — flip for alignment.
    r_blups = pastes_ref["ranef"]["cask:batch"]["(Intercept)"]
    il_blups = pastes_fit.random_effects["batch:cask"]
    # Reverse each lme4 label "a:A" → "A:a" to match interlace convention
    labels = sorted(il_blups.keys())
    il_arr = np.array([il_blups[g] for g in labels])
    r_arr = np.array([r_blups[":".join(reversed(g.split(":")))] for g in labels])
    corr = np.corrcoef(r_arr, il_arr)[0, 1]
    assert corr > 0.99, f"batch:cask BLUP correlation={corr:.4f} < 0.99"


def test_pastes_residuals(pastes_fit, pastes_ref):
    r_resid = np.array(pastes_ref["resid_cond"])
    corr = np.corrcoef(pastes_fit.resid, r_resid)[0, 1]
    assert corr > 0.999, f"Residual correlation={corr:.6f} < 0.999"
