"""Tests for cumulative link mixed models (CLMM).

Validates interlace.clmm() against R's ordinal::clmm() on the wine dataset.
Reference values generated by tests/fixtures/gen_clmm_parity.R.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import interlace

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture()
def wine_data() -> pd.DataFrame:
    """Load the wine tasting dataset used by ordinal::clmm()."""
    return pd.read_csv(FIXTURES / "clmm_parity_data.csv")


@pytest.fixture()
def r_results() -> dict:
    """Load R reference results from ordinal::clmm()."""
    with open(FIXTURES / "clmm_parity_r_results.json") as f:
        return json.load(f)


# ---- Logit link parity ----


class TestCLMMLogitParity:
    """Parity with R ordinal::clmm(..., link='logit') on wine data."""

    @pytest.fixture(autouse=True)
    def _fit(self, wine_data: pd.DataFrame, r_results: dict) -> None:
        self.r = r_results["logit"]
        self.result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            groups="judge",
            link="logit",
        )

    def test_thresholds(self) -> None:
        """Threshold estimates match R within 1e-2."""
        r_thresh = self.r["thresholds"]
        for name, r_val in r_thresh.items():
            py_val = self.result.thresholds[name]
            assert abs(py_val - r_val) < 1e-2, (
                f"Threshold {name}: python={py_val:.6f}, R={r_val:.6f}"
            )

    def test_fixed_effects(self) -> None:
        """Fixed effect estimates match R within 1e-2."""
        r_vals = list(self.r["betas"].values())
        py_vals = list(self.result.fe_params.values)
        assert len(py_vals) == len(r_vals)
        for i, (py_val, r_val) in enumerate(zip(py_vals, r_vals, strict=True)):
            assert abs(py_val - r_val) < 1e-2, (
                f"Beta[{i}]: python={py_val:.6f}, R={r_val:.6f}"
            )

    def test_fixed_effect_se(self) -> None:
        """Fixed effect SEs match R within 1% relative."""
        r_vals = list(self.r["beta_se"].values())
        py_vals = list(self.result.fe_bse.values)
        assert len(py_vals) == len(r_vals)
        for i, (py_val, r_val) in enumerate(zip(py_vals, r_vals, strict=True)):
            rel = abs(py_val - r_val) / r_val
            assert rel < 0.01, (
                f"SE[{i}]: python={py_val:.6f}, R={r_val:.6f}, rel={rel:.4f}"
            )

    def test_threshold_se(self) -> None:
        """Threshold SEs match R within 1% relative."""
        r_se = self.r["threshold_se"]
        for name, r_val in r_se.items():
            py_val = self.result.threshold_bse[name]
            rel = abs(py_val - r_val) / r_val
            assert rel < 0.01, (
                f"Threshold SE {name}: py={py_val:.6f}, R={r_val:.6f}, rel={rel:.4f}"
            )

    def test_variance_component(self) -> None:
        """RE variance matches R within 5% relative."""
        r_var = self.r["re_var_judge"]
        py_var = self.result.variance_components["judge"]
        rel = abs(py_var - r_var) / r_var
        assert rel < 0.05, f"RE var: python={py_var:.6f}, R={r_var:.6f}, rel={rel:.4f}"

    def test_loglikelihood(self) -> None:
        """Log-likelihood matches R within 0.5."""
        r_ll = self.r["loglik"]
        py_ll = self.result.llf
        assert abs(py_ll - r_ll) < 0.5, f"logLik: python={py_ll:.4f}, R={r_ll:.4f}"

    def test_blups_correlation(self) -> None:
        """BLUPs correlate > 0.99 with R conditional modes."""
        r_blups = self.r["blups_judge"]
        py_re = self.result.random_effects["judge"]
        # R keys are strings, Python index may be int — align by sorted order
        r_levels = sorted(r_blups.keys(), key=lambda x: int(x))
        r_vec = np.array([r_blups[k] for k in r_levels])
        py_vec = np.array(py_re.values)
        assert len(py_vec) == len(r_vec)
        corr = np.corrcoef(r_vec, py_vec)[0, 1]
        assert corr > 0.99, f"BLUP correlation: {corr:.6f}"

    def test_converged(self) -> None:
        assert self.result.converged


# ---- Probit link parity ----


class TestCLMMProbitParity:
    """Parity with R ordinal::clmm(..., link='probit') on wine data."""

    @pytest.fixture(autouse=True)
    def _fit(self, wine_data: pd.DataFrame, r_results: dict) -> None:
        self.r = r_results["probit"]
        self.result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            groups="judge",
            link="probit",
        )

    def test_thresholds(self) -> None:
        r_thresh = self.r["thresholds"]
        for name, r_val in r_thresh.items():
            py_val = self.result.thresholds[name]
            assert abs(py_val - r_val) < 1e-2, (
                f"Threshold {name}: python={py_val:.6f}, R={r_val:.6f}"
            )

    def test_fixed_effects(self) -> None:
        r_vals = list(self.r["betas"].values())
        py_vals = list(self.result.fe_params.values)
        assert len(py_vals) == len(r_vals)
        for i, (py_val, r_val) in enumerate(zip(py_vals, r_vals, strict=True)):
            assert abs(py_val - r_val) < 1e-2, (
                f"Beta[{i}]: python={py_val:.6f}, R={r_val:.6f}"
            )

    def test_variance_component(self) -> None:
        r_var = self.r["re_var_judge"]
        py_var = self.result.variance_components["judge"]
        rel = abs(py_var - r_var) / r_var
        assert rel < 0.05, f"RE var: python={py_var:.6f}, R={r_var:.6f}, rel={rel:.4f}"

    def test_loglikelihood(self) -> None:
        r_ll = self.r["loglik"]
        py_ll = self.result.llf
        assert abs(py_ll - r_ll) < 0.5, f"logLik: python={py_ll:.4f}, R={r_ll:.4f}"


# ---- API and edge-case tests ----


class TestCLMMAPI:
    """Basic API contract tests for interlace.clmm()."""

    def test_result_has_expected_attributes(self, wine_data: pd.DataFrame) -> None:
        result = interlace.clmm("rating ~ temp + contact", wine_data, groups="judge")
        assert hasattr(result, "thresholds")
        assert hasattr(result, "threshold_bse")
        assert hasattr(result, "fe_params")
        assert hasattr(result, "fe_bse")
        assert hasattr(result, "random_effects")
        assert hasattr(result, "variance_components")
        assert hasattr(result, "llf")
        assert hasattr(result, "aic")
        assert hasattr(result, "bic")
        assert hasattr(result, "converged")
        assert hasattr(result, "nobs")

    def test_threshold_ordering(self, wine_data: pd.DataFrame) -> None:
        """Thresholds must be strictly increasing."""
        result = interlace.clmm("rating ~ temp + contact", wine_data, groups="judge")
        vals = list(result.thresholds.values())
        for i in range(1, len(vals)):
            assert vals[i] > vals[i - 1], f"Thresholds not increasing: {vals}"

    def test_cloglog_link_runs(self, wine_data: pd.DataFrame) -> None:
        """cloglog link should run without error."""
        result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            groups="judge",
            link="cloglog",
        )
        assert result.converged

    def test_bad_link_raises(self, wine_data: pd.DataFrame) -> None:
        with pytest.raises(ValueError, match="link"):
            interlace.clmm(
                "rating ~ temp + contact",
                wine_data,
                groups="judge",
                link="identity",
            )


# ---- predict() tests ----


class TestCLMMPredict:
    """Tests for CLMMResult.predict()."""

    @pytest.fixture(autouse=True)
    def _fit(self, wine_data: pd.DataFrame) -> None:
        self.data = wine_data
        self.result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            groups="judge",
            link="logit",
        )

    def test_predict_prob_shape(self) -> None:
        """predict(type='prob') returns (n, K) array."""
        probs = self.result.predict(self.data, type="prob")
        assert probs.shape == (len(self.data), 5)  # 5 rating levels

    def test_predict_prob_sums_to_one(self) -> None:
        """Category probabilities sum to 1 for each observation."""
        probs = self.result.predict(self.data, type="prob")
        row_sums = probs.sum(axis=1)
        np.testing.assert_allclose(row_sums, 1.0, atol=1e-8)

    def test_predict_prob_nonneg(self) -> None:
        """All predicted probabilities are non-negative."""
        probs = self.result.predict(self.data, type="prob")
        assert np.all(probs >= 0)

    def test_predict_prob_le_one(self) -> None:
        """All predicted probabilities are <= 1."""
        probs = self.result.predict(self.data, type="prob")
        assert np.all(probs <= 1.0)

    def test_predict_cum_prob_shape(self) -> None:
        """predict(type='cum.prob') returns (n, K-1) array."""
        cum = self.result.predict(self.data, type="cum.prob")
        assert cum.shape == (len(self.data), 4)  # K-1 = 4

    def test_predict_cum_prob_monotone(self) -> None:
        """Cumulative probabilities are non-decreasing across categories."""
        cum = self.result.predict(self.data, type="cum.prob")
        for j in range(1, cum.shape[1]):
            assert np.all(cum[:, j] >= cum[:, j - 1] - 1e-10)

    def test_predict_cum_prob_bounded(self) -> None:
        """Cumulative probabilities are in [0, 1]."""
        cum = self.result.predict(self.data, type="cum.prob")
        assert np.all(cum >= -1e-10)
        assert np.all(cum <= 1.0 + 1e-10)

    def test_predict_linear_predictor_shape(self) -> None:
        """predict(type='linear.predictor') returns (n,) array."""
        eta = self.result.predict(self.data, type="linear.predictor")
        assert eta.shape == (len(self.data),)

    def test_predict_unseen_group_shrinks_to_zero(self) -> None:
        """Unseen groups get zero random effect (fixed-effects only)."""
        new_data = pd.DataFrame(
            {
                "temp": ["cold", "warm"],
                "contact": ["no", "yes"],
                "judge": ["UNSEEN_A", "UNSEEN_B"],
            }
        )
        probs = self.result.predict(new_data, type="prob")
        assert probs.shape == (2, 5)
        np.testing.assert_allclose(probs.sum(axis=1), 1.0, atol=1e-8)

    def test_predict_prob_consistent_with_cum_prob(self) -> None:
        """prob[:,k] should equal cum[:,k] - cum[:,k-1]."""
        probs = self.result.predict(self.data, type="prob")
        cum = self.result.predict(self.data, type="cum.prob")
        # P(Y=1) = cum[:,0]
        np.testing.assert_allclose(probs[:, 0], cum[:, 0], atol=1e-8)
        # P(Y=k) = cum[:,k-1] - cum[:,k-2] for k=2..K-1
        for k in range(1, probs.shape[1] - 1):
            np.testing.assert_allclose(
                probs[:, k], cum[:, k] - cum[:, k - 1], atol=1e-8
            )
        # P(Y=K) = 1 - cum[:,-1]
        np.testing.assert_allclose(probs[:, -1], 1.0 - cum[:, -1], atol=1e-8)

    def test_predict_bad_type_raises(self) -> None:
        with pytest.raises(ValueError, match="type"):
            self.result.predict(self.data, type="class")


# ---- Crossed random effects test ----


class TestCLMMCrossedRE:
    """Test CLMM with crossed random effects (judge + bottle)."""

    def test_crossed_re_converges(self, wine_data: pd.DataFrame) -> None:
        """CLMM with (1|judge) + (1|bottle) should converge."""
        result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            random=["(1|judge)", "(1|bottle)"],
            link="logit",
        )
        assert result.converged

    def test_crossed_re_has_both_groups(self, wine_data: pd.DataFrame) -> None:
        """Both grouping factors should appear in random_effects."""
        result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            random=["(1|judge)", "(1|bottle)"],
            link="logit",
        )
        assert "judge" in result.random_effects
        assert "bottle" in result.random_effects
        assert "judge" in result.variance_components
        assert "bottle" in result.variance_components

    def test_crossed_re_variance_positive(self, wine_data: pd.DataFrame) -> None:
        """Both variance components should be non-negative."""
        result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            random=["(1|judge)", "(1|bottle)"],
            link="logit",
        )
        assert result.variance_components["judge"] >= 0
        assert result.variance_components["bottle"] >= 0


# ---- confint() tests ----


class TestCLMMConfint:
    """Tests for CLMMResult.confint()."""

    @pytest.fixture(autouse=True)
    def _fit(self, wine_data: pd.DataFrame) -> None:
        self.result = interlace.clmm(
            "rating ~ temp + contact",
            wine_data,
            groups="judge",
            link="logit",
        )

    def test_confint_returns_dataframe(self) -> None:
        """confint() should return a DataFrame."""
        ci = self.result.confint()
        assert isinstance(ci, pd.DataFrame)

    def test_confint_shape(self) -> None:
        """confint() has rows for thresholds + fixed effects, 2 columns."""
        ci = self.result.confint()
        n_thresh = len(self.result.thresholds)
        n_fe = len(self.result.fe_params)
        assert ci.shape == (n_thresh + n_fe, 2)

    def test_confint_lower_lt_upper(self) -> None:
        """Lower bound < upper bound for all parameters."""
        ci = self.result.confint()
        assert np.all(ci.iloc[:, 0] < ci.iloc[:, 1])

    def test_confint_contains_estimate(self) -> None:
        """Point estimates fall within the confidence interval."""
        ci = self.result.confint()
        thresh_vals = list(self.result.thresholds.values())
        fe_vals = list(self.result.fe_params.values)
        estimates = thresh_vals + fe_vals
        for i, est in enumerate(estimates):
            assert ci.iloc[i, 0] <= est <= ci.iloc[i, 1]

    def test_confint_custom_level(self) -> None:
        """99% CI should be wider than 95% CI."""
        ci_95 = self.result.confint(level=0.95)
        ci_99 = self.result.confint(level=0.99)
        width_95 = ci_95.iloc[:, 1] - ci_95.iloc[:, 0]
        width_99 = ci_99.iloc[:, 1] - ci_99.iloc[:, 0]
        assert np.all(width_99 > width_95)
