"""Parity tests: KR variance-covariance derivatives vs R's pbkrtest/lmerTest.

Compares interlace model parameters against R lme4 on the same data, then
verifies our KR derivatives produce a bias correction consistent with R's
vcovAdj output.

Reference values generated by: Rscript tests/fixtures/gen_kr_parity.R
Requires: lme4, pbkrtest, lmerTest, jsonlite
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import interlace
from interlace.kr_vcov import kr_vcov_derivs

FIXTURES = Path(__file__).parent / "fixtures"


def _load_fixture(name: str) -> dict:
    with open(FIXTURES / name) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# One-factor model: y ~ x + (1 | group)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def one_factor():
    """Load R fixture and fit the same model in interlace."""
    ref = _load_fixture("kr_parity_one_factor.json")
    df = pd.DataFrame(
        {
            "y": np.array(ref["y"]),
            "x": np.array(ref["x"]),
            "group": [str(g) for g in ref["group"]],
        }
    )
    result = interlace.fit("y ~ x", data=df, groups="group")
    return ref, result


class TestOneFactorModelParity:
    """Verify interlace model matches R lme4 on the same data."""

    def test_theta_matches_r(self, one_factor):
        ref, result = one_factor
        r_theta = list(ref["theta"].values())
        np.testing.assert_allclose(result.theta, r_theta, rtol=0.01)

    def test_beta_matches_r(self, one_factor):
        ref, result = one_factor
        r_beta = list(ref["beta"].values())
        np.testing.assert_allclose(np.array(result.fe_params), r_beta, atol=1e-3)

    def test_sigma_matches_r(self, one_factor):
        ref, result = one_factor
        np.testing.assert_allclose(np.sqrt(result.scale), ref["sigma"], rtol=0.01)

    def test_fe_cov_matches_r(self, one_factor):
        ref, result = one_factor
        r_fe_cov = np.array(ref["fe_cov"])
        np.testing.assert_allclose(result.fe_cov, r_fe_cov, rtol=0.01)


class TestOneFactorKRDerivatives:
    """Validate KR derivatives against R's vcovAdj output."""

    def test_kr_bias_correction_direction(self, one_factor):
        """The simple bias correction should move fe_cov toward R's vcovAdj."""
        ref, result = one_factor
        kr = kr_vcov_derivs(result)

        # R's KR correction
        r_kr_adj = np.array(ref["kr_vcov_adj"])
        r_correction = r_kr_adj - np.array(ref["fe_cov"])

        # Our simple second-order bias correction: 0.5 * sum_ij Phi_ij * d2C_ij
        k = len(result.theta)
        bias_correction = np.zeros_like(kr.fe_cov)
        for i in range(k):
            for j in range(k):
                bias_correction += 0.5 * kr.Phi[i, j] * kr.d2C[i, j]

        # The corrections should have the same sign on the diagonal
        # (KR typically inflates variance estimates)
        r_diag = np.diag(r_correction)
        our_diag = np.diag(bias_correction)
        # At least the sign should agree for the majority of entries
        nonzero = np.abs(r_diag) > 1e-10
        if np.any(nonzero):
            sign_agreement = np.sign(r_diag[nonzero]) == np.sign(our_diag[nonzero])
            assert np.mean(sign_agreement) >= 0.5, (
                f"Bias correction signs disagree: R={r_diag}, ours={our_diag}"
            )

    def test_kr_correction_magnitude_reasonable(self, one_factor):
        """The bias correction should be small relative to fe_cov."""
        ref, result = one_factor
        kr = kr_vcov_derivs(result)

        k = len(result.theta)
        bias_correction = np.zeros_like(kr.fe_cov)
        for i in range(k):
            for j in range(k):
                bias_correction += 0.5 * kr.Phi[i, j] * kr.d2C[i, j]

        # The correction should be < 50% of fe_cov diagonal
        ratio = np.abs(np.diag(bias_correction)) / np.abs(np.diag(kr.fe_cov))
        assert np.all(ratio < 0.5), (
            f"Bias correction too large relative to fe_cov: ratio={ratio}"
        )


# ---------------------------------------------------------------------------
# Two-factor model: y ~ x + (1 | g1) + (1 | g2)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def two_factor():
    """Load R fixture and fit the same model in interlace."""
    ref = _load_fixture("kr_parity_two_factor.json")
    df = pd.DataFrame(
        {
            "y": np.array(ref["y"]),
            "x": np.array(ref["x"]),
            "g1": [str(g) for g in ref["g1"]],
            "g2": [str(g) for g in ref["g2"]],
        }
    )
    result = interlace.fit("y ~ x", data=df, random=["(1|g1)", "(1|g2)"])
    return ref, result


class TestTwoFactorModelParity:
    """Verify interlace model matches R lme4 on the same data."""

    def test_theta_matches_r(self, two_factor):
        ref, result = two_factor
        r_theta = list(ref["theta"].values())
        np.testing.assert_allclose(np.sort(result.theta), np.sort(r_theta), rtol=0.02)

    def test_beta_matches_r(self, two_factor):
        ref, result = two_factor
        r_beta = list(ref["beta"].values())
        np.testing.assert_allclose(np.array(result.fe_params), r_beta, atol=1e-2)

    def test_sigma_matches_r(self, two_factor):
        ref, result = two_factor
        np.testing.assert_allclose(np.sqrt(result.scale), ref["sigma"], rtol=0.02)

    def test_fe_cov_matches_r(self, two_factor):
        ref, result = two_factor
        r_fe_cov = np.array(ref["fe_cov"])
        np.testing.assert_allclose(result.fe_cov, r_fe_cov, rtol=0.02)


class TestTwoFactorKRDerivatives:
    """Validate KR derivatives against R's vcovAdj for the crossed model."""

    def test_kr_derivatives_finite(self, two_factor):
        _, result = two_factor
        kr = kr_vcov_derivs(result)
        assert np.all(np.isfinite(kr.dC))
        assert np.all(np.isfinite(kr.d2C))
        assert np.all(np.isfinite(kr.Phi))

    def test_kr_correction_same_sign_as_r(self, two_factor):
        """The KR diagonal correction should agree in sign with R's vcovAdj."""
        ref, result = two_factor
        kr = kr_vcov_derivs(result)

        r_kr_adj = np.array(ref["kr_vcov_adj"])
        r_correction_diag = np.diag(r_kr_adj) - np.diag(np.array(ref["fe_cov"]))

        k = len(result.theta)
        bias_correction = np.zeros_like(kr.fe_cov)
        for i in range(k):
            for j in range(k):
                bias_correction += 0.5 * kr.Phi[i, j] * kr.d2C[i, j]

        our_correction_diag = np.diag(bias_correction)

        # For entries where R's correction is non-negligible, signs should agree
        nonzero = np.abs(r_correction_diag) > 1e-10
        if np.any(nonzero):
            sign_ok = np.sign(r_correction_diag[nonzero]) == np.sign(
                our_correction_diag[nonzero]
            )
            assert np.mean(sign_ok) >= 0.5, (
                f"Sign mismatch: R correction={r_correction_diag}, "
                f"ours={our_correction_diag}"
            )

    def test_r_kr_reference_stored(self, two_factor):
        """Verify R's kr_vcov_adj and kr_dfs are stored for downstream use.

        The full KR formula (C_KR = C + 2*Lambda) requires V-derivatives in
        the original variance-component parameterisation, not the profiled
        theta parameterisation that our C-derivatives use.  The downstream
        task (interlace-sbo) will implement the correct mapping and validate
        against these R reference values.
        """
        ref, _ = two_factor
        r_kr_adj = np.array(ref["kr_vcov_adj"])
        r_kr_dfs = ref["kr_dfs"]
        # Just verify the reference data is present and well-formed
        assert r_kr_adj.shape == (2, 2)
        assert len(r_kr_dfs) == 2
        assert all(v > 0 for v in r_kr_dfs.values())
